# These are supported funding model platforms

github: # [@FabianaCampanari]
open_collective: # Replace with a single Open Collective username
custom: # ['https://github.com/FabianaCampanari/NerdFlix']
